language: go

go:
  - 1.8.3

before_install:
  - go get github.com/mattn/goveralls

branches:
  only:
    - master

script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci

sudo: false